# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: CmdLine@2
  inputs:
    script: 'sudo apt-get update sudo apt-get install -y golang-go'
  displayName: 'Instalacion GO'

- task: CmdLine@2
  inputs:
    script: 'go version'
  displayName: 'Version Go'