export const paths = {
    APP: "/app",
    APPCOMPENSACION: "/app/compensacion",
    APPHOME: "/app/inicio",
    APPREGISTROS: "/app/registros",
    APPREGISTROSREPORTES: "/app/registros/reporte/:reportId",
    APPRESULTADOS: "/app/resultados",
    APPRESULTADOSEMPRESA: "/app/resultados/empresa/:companyId",
    APPRESULTADOSEMPRESADETALLE: "/app/resultados/empresa/detalle/:companyDetailId",
    CONTACT: "/contact",
    HOME: "/",
    LOGIN: "/login",
    PRECIOS: "/precios",
    RECOVERPASSWORD: "/recover-password",
    RECOVERPASSWORDCOMPLETION: "/recover-password-completion",
    REGISTER: "/register",
}