export const paths = {
    APP: "/app",
    APPCOMPENSACION: "/app/compensation",
    APPHOME: "/app/start",
    APPREGISTROS: "/app/records",
    APPREGISTROSREPORTES: "/app/records/report/:reportId",
    APPRESULTADOS: "/app/results",
    APPRESULTADOSEMPRESA: "/app/results/company/:companyId",
    APPRESULTADOSEMPRESADETALLE: "/app/results/company/detail/:companyDetailId",
    CONTACT: "/contact",
    HOME: "/",
    LOGIN: "/login",
    PRECIOS: "/prices",
    RECOVERPASSWORD: "/recover-password",
    RECOVERPASSWORDCOMPLETION: "/recover-password-completion",
    REGISTER: "/register",
    REGISTERCOMPLETION: "/register-completion",
}